
import "./globals.css";
import Navbar from "./ui/navbar";


export const metadata = {
  title: "Fabricant de meubles de cuisine de lux. - Intercocina",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head> 

      </head>
      <body className={`antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
